import type { AuraLedgerEntry } from "@/types";

export const MOCK_AURA_HISTORY: AuraLedgerEntry[] = [
  {
    id: "ledger-1",
    userId: "user-maya",
    amount: 120,
    reason: "aura_received",
    description: 'Aura from your "helped a classmate" moment',
    relatedMomentId: "moment-5",
    createdAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
  {
    id: "ledger-2",
    userId: "user-maya",
    amount: 150,
    reason: "streak_bonus_7",
    description: "7-day streak bonus",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
  },
  {
    id: "ledger-3",
    userId: "user-maya",
    amount: 20,
    reason: "moment_posted",
    description: "Posted an Aura moment",
    relatedMomentId: "moment-5",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
  },
  {
    id: "ledger-4",
    userId: "user-maya",
    amount: 25,
    reason: "positive_comment",
    description: "Left a positive comment on Riya's moment",
    relatedUserId: "user-riya",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 9).toISOString(),
  },
  {
    id: "ledger-5",
    userId: "user-maya",
    amount: 80,
    reason: "challenge_completed",
    description: 'Completed "Good Vibes Only" challenge',
    relatedChallengeId: "challenge-1",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
  {
    id: "ledger-6",
    userId: "user-maya",
    amount: -30,
    reason: "negative_comment",
    description: "Comment removed for community guideline violation",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
  },
  {
    id: "ledger-7",
    userId: "user-maya",
    amount: 15,
    reason: "aura_received",
    description: "Aura from a friend on your moment",
    relatedUserId: "user-noah",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
  },
  {
    id: "ledger-8",
    userId: "user-maya",
    amount: 100,
    reason: "level_milestone",
    description: "Reached Level 6 — Luminous",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
  },
  {
    id: "ledger-9",
    userId: "user-maya",
    amount: 30,
    reason: "daily_opportunity",
    description: "Completed daily Aura opportunity",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 96).toISOString(),
  },
  {
    id: "ledger-10",
    userId: "user-maya",
    amount: 50,
    reason: "streak_bonus_3",
    description: "3-day streak bonus",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 120).toISOString(),
  },
  {
    id: "ledger-11",
    userId: "user-maya",
    amount: 20,
    reason: "moment_posted",
    description: "Posted an Aura moment",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 144).toISOString(),
  },
  {
    id: "ledger-12",
    userId: "user-maya",
    amount: 140,
    reason: "challenge_completed",
    description: 'Completed "Quiet Aura" challenge',
    relatedChallengeId: "challenge-6",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 168).toISOString(),
  },
  {
    id: "ledger-13",
    userId: "user-maya",
    amount: 18,
    reason: "aura_received",
    description: "Aura from Hana on your moment",
    relatedUserId: "user-hana",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 180).toISOString(),
  },
  {
    id: "ledger-14",
    userId: "user-maya",
    amount: -15,
    reason: "reciprocal_abuse",
    description: "Aura farming detected — reciprocal pattern flagged",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 200).toISOString(),
  },
  {
    id: "ledger-15",
    userId: "user-maya",
    amount: 20,
    reason: "moment_posted",
    description: "Posted an Aura moment",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 216).toISOString(),
  },
];
