import type { Challenge } from "@/types";
import { MOCK_FRIENDS } from "./users";

const [riya, noah, samira, leo, hana, ishan, amara, eli, sofia] = MOCK_FRIENDS;

export const MOCK_CHALLENGES: Challenge[] = [
  {
    id: "challenge-1",
    title: "Good Vibes Only",
    description: "Give someone a genuine compliment — not about their appearance, but something that actually matters.",
    task: "Give someone a genuine, specific compliment today.",
    difficulty: "Easy",
    auraReward: 50,
    participantCount: 3841,
    friendParticipants: [riya, noah, eli],
    recentCompletions: [
      { user: riya, completedAt: new Date(Date.now() - 1000 * 60 * 40).toISOString() },
      { user: eli, completedAt: new Date(Date.now() - 1000 * 60 * 120).toISOString() },
    ],
  },
  {
    id: "challenge-2",
    title: "The Check-In",
    description: "Reach out to someone you haven't spoken to in a while. Sometimes just showing up matters.",
    task: "Check in on someone you haven't spoken to recently.",
    difficulty: "Easy",
    auraReward: 60,
    participantCount: 5210,
    friendParticipants: [hana, samira],
    recentCompletions: [
      { user: hana, completedAt: new Date(Date.now() - 1000 * 60 * 60).toISOString() },
    ],
  },
  {
    id: "challenge-3",
    title: "Tiny Aura",
    description: "Small acts of helpfulness are still Aura. No grand gesture needed.",
    task: "Do one small helpful thing without being asked.",
    difficulty: "Easy",
    auraReward: 40,
    participantCount: 7892,
    friendParticipants: [ishan, riya, leo],
    recentCompletions: [
      { user: ishan, completedAt: new Date(Date.now() - 1000 * 60 * 90).toISOString() },
    ],
  },
  {
    id: "challenge-4",
    title: "Pass It On",
    description: "Do something good and bring a friend along. Good energy spreads.",
    task: "Help someone today and invite one friend to try the challenge.",
    difficulty: "Easy",
    auraReward: 70,
    participantCount: 2184,
    friendParticipants: [amara, noah],
    recentCompletions: [],
  },
  {
    id: "challenge-5",
    title: "Stranger Aura",
    description: "Do something kind for someone you don't know. The best kind of plot twist.",
    task: "Do something kind for someone you don't know.",
    difficulty: "Medium",
    auraReward: 120,
    participantCount: 4432,
    friendParticipants: [leo, noah, samira, amara],
    recentCompletions: [
      { user: noah, completedAt: new Date(Date.now() - 1000 * 60 * 200).toISOString() },
    ],
  },
  {
    id: "challenge-6",
    title: "Quiet Aura",
    description: "Do something good without expecting anyone to notice. That's the real flex.",
    task: "Do something good without expecting recognition.",
    difficulty: "Medium",
    auraReward: 140,
    participantCount: 6129,
    friendParticipants: [eli, hana],
    recentCompletions: [
      { user: hana, completedAt: new Date(Date.now() - 1000 * 60 * 300).toISOString() },
      { user: eli, completedAt: new Date(Date.now() - 1000 * 60 * 480).toISOString() },
    ],
  },
  {
    id: "challenge-7",
    title: "Make Their Day",
    description: "One thoughtful gesture, directed at one specific person. That's all.",
    task: "Do something thoughtful specifically for another person.",
    difficulty: "Medium",
    auraReward: 150,
    participantCount: 3876,
    friendParticipants: [sofia, riya, amara],
    recentCompletions: [
      { user: amara, completedAt: new Date(Date.now() - 1000 * 60 * 150).toISOString() },
    ],
  },
  {
    id: "challenge-8",
    title: "3-Day Aura Run",
    description: "Three days. Three moments. Build the habit.",
    task: "Complete and share one Aura moment for 3 consecutive days.",
    difficulty: "Medium",
    auraReward: 300,
    streakRequirement: 3,
    participantCount: 2341,
    friendParticipants: [noah, hana, riya],
    recentCompletions: [
      { user: noah, completedAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString() },
    ],
  },
  {
    id: "challenge-9",
    title: "7 Days of Aura",
    description: "One week. Prove it wasn't a phase.",
    task: "Maintain a 7-day good-action streak.",
    difficulty: "Hard",
    auraReward: 800,
    streakRequirement: 7,
    participantCount: 1024,
    friendParticipants: [amara, hana],
    recentCompletions: [
      { user: amara, completedAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString() },
    ],
  },
  {
    id: "challenge-10",
    title: "Aura Machine",
    description: "The ultimate test. Five challenges. Fourteen days. Legendary status awaits.",
    task: "Complete 5 different challenges while maintaining a 14-day Aura streak.",
    difficulty: "Legendary",
    auraReward: 2500,
    streakRequirement: 14,
    participantCount: 128,
    friendParticipants: [amara],
    recentCompletions: [],
  },
];
