import type { AuraMoment } from "@/types";
import { MOCK_FRIENDS, DEMO_USERS } from "./users";

const maya = DEMO_USERS.maya;
const [riya, noah, samira, leo, hana, ishan, amara, eli, sofia, kabir] = MOCK_FRIENDS;

export const MOCK_MOMENTS: AuraMoment[] = [
  {
    id: "moment-1",
    authorId: riya.id,
    author: riya,
    caption: "Grabbed an extra coffee for the security guard downstairs. He remembered my name before I remembered his 😭",
    mediaUrl: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&h=400&fit=crop",
    mediaType: "image",
    auraCardId: "4",
    auraCardText: "Tiny deed. Big Aura.",
    visibility: "friends",
    auraCount: 142,
    commentCount: 8,
    hasGivenAura: false,
    location: "Bengaluru",
    createdAt: new Date(Date.now() - 1000 * 60 * 32).toISOString(),
  },
  {
    id: "moment-2",
    authorId: noah.id,
    author: noah,
    caption: "My friend had a horrible presentation day so I just sat with him after class. No advice. Just listened.",
    visibility: "friends",
    auraCount: 218,
    commentCount: 14,
    hasGivenAura: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 68).toISOString(),
  },
  {
    id: "moment-3",
    authorId: hana.id,
    author: hana,
    caption: "Called my grandma for 'five minutes'. We spoke for 47.",
    mediaUrl: "https://images.unsplash.com/photo-1521791136064-7986c2920216?w=600&h=400&fit=crop",
    mediaType: "image",
    auraCardId: "5",
    auraCardText: "Quiet Aura hits different",
    visibility: "friends",
    auraCount: 356,
    commentCount: 22,
    hasGivenAura: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 140).toISOString(),
  },
  {
    id: "moment-4",
    authorId: samira.id,
    author: samira,
    caption: "Picked up trash on my walk because apparently my main character arc is municipal services now.",
    mediaUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=400&fit=crop",
    mediaType: "image",
    visibility: "public",
    challengeId: "challenge-7",
    challengeTitle: "Stranger Aura",
    auraCount: 189,
    commentCount: 17,
    hasGivenAura: false,
    location: "Dubai",
    createdAt: new Date(Date.now() - 1000 * 60 * 210).toISOString(),
  },
  {
    id: "moment-5",
    authorId: maya.id,
    author: maya,
    caption: "Helped my neighbor carry groceries upstairs. Tiny thing, but she looked so relieved.",
    auraCardId: "4",
    auraCardText: "Tiny deed. Big Aura.",
    visibility: "friends",
    auraCount: 97,
    commentCount: 6,
    hasGivenAura: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 280).toISOString(),
  },
  {
    id: "moment-6",
    authorId: leo.id,
    author: leo,
    caption: "Someone looked totally lost at the metro. Walked them to their stop. Made us both late but somehow neither of us minded.",
    visibility: "friends",
    auraCount: 274,
    commentCount: 19,
    hasGivenAura: true,
    location: "Barcelona",
    createdAt: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
  },
  {
    id: "moment-7",
    authorId: amara.id,
    author: amara,
    caption: "Organized a spontaneous study session for everyone stressing about finals. Brought snacks. Nobody failed.",
    mediaUrl: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=600&h=400&fit=crop",
    mediaType: "image",
    auraCardId: "9",
    auraCardText: "Good energy only",
    visibility: "friends",
    challengeId: "challenge-5",
    challengeTitle: "Make Their Day",
    auraCount: 441,
    commentCount: 31,
    hasGivenAura: false,
    location: "Lagos",
    createdAt: new Date(Date.now() - 1000 * 60 * 420).toISOString(),
  },
  {
    id: "moment-8",
    authorId: eli.id,
    author: eli,
    caption: "Left an encouraging note on a classmate's laptop. Anonymous. That's the whole point.",
    visibility: "friends",
    auraCount: 163,
    commentCount: 11,
    hasGivenAura: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 510).toISOString(),
  },
  {
    id: "moment-9",
    authorId: ishan.id,
    author: ishan,
    caption: "Someone dropped their metro card and didn't notice. Sprint training finally useful.",
    auraCardId: "6",
    auraCardText: "Did it for the Aura",
    visibility: "friends",
    auraCount: 88,
    commentCount: 5,
    hasGivenAura: true,
    location: "Bengaluru",
    createdAt: new Date(Date.now() - 1000 * 60 * 600).toISOString(),
  },
  {
    id: "moment-10",
    authorId: sofia.id,
    author: sofia,
    caption: "Covered for my colleague during a rough meeting. She texted me later saying I'm her favorite person today. Mission accomplished.",
    mediaUrl: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=600&h=400&fit=crop",
    mediaType: "image",
    visibility: "friends",
    auraCount: 312,
    commentCount: 26,
    hasGivenAura: false,
    location: "Milan",
    createdAt: new Date(Date.now() - 1000 * 60 * 720).toISOString(),
  },
  {
    id: "moment-11",
    authorId: kabir.id,
    author: kabir,
    caption: "Finally texted back that friend I've been meaning to for three weeks. Small thing but it clearly mattered to them.",
    visibility: "friends",
    auraCount: 121,
    commentCount: 9,
    hasGivenAura: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 840).toISOString(),
  },
  {
    id: "moment-12",
    authorId: noah.id,
    author: noah,
    caption: "Saw someone eating alone at lunch. Sat down. Turns out they just moved here. We're hanging out this weekend.",
    auraCardId: "10",
    auraCardText: "Main character Aura",
    visibility: "friends",
    challengeId: "challenge-8",
    challengeTitle: "Stranger Aura",
    auraCount: 528,
    commentCount: 41,
    hasGivenAura: true,
    location: "Seoul",
    createdAt: new Date(Date.now() - 1000 * 60 * 960).toISOString(),
  },
  {
    id: "moment-13",
    authorId: riya.id,
    author: riya,
    caption: "spent my lunch break teaching the aunty next door how to video call her grandkids. she cried. i cried. we both cried ngl 😭",
    mediaUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    mediaType: "video",
    auraCardId: "4",
    auraCardText: "Tiny deed. Big Aura.",
    visibility: "public",
    auraCount: 312,
    commentCount: 19,
    hasGivenAura: false,
    location: "Bengaluru",
    createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: "moment-14",
    authorId: noah.id,
    author: noah,
    caption: "picked up a whole bag of trash on my morning run and somehow it made the run feel more meaningful than any PR ever has",
    mediaUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    mediaType: "video",
    visibility: "public",
    challengeId: "challenge-7",
    challengeTitle: "Stranger Aura",
    auraCount: 187,
    commentCount: 14,
    hasGivenAura: true,
    location: "Seoul",
    createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
  },
  {
    id: "moment-15",
    authorId: hana.id,
    author: hana,
    caption: "left flowers on my neighbor's doorstep bc they've been going through it lately. anonymous aura is the best aura fr",
    mediaUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
    mediaType: "video",
    auraCardId: "5",
    auraCardText: "Quiet Aura hits different",
    visibility: "public",
    auraCount: 401,
    commentCount: 28,
    hasGivenAura: false,
    location: "Tokyo",
    createdAt: new Date(Date.now() - 1000 * 60 * 150).toISOString(),
  },
  {
    id: "moment-16",
    authorId: amara.id,
    author: amara,
    caption: "organized a free study session for first-gen students who can't afford tutors. 23 people showed up. that's the energy rn",
    mediaUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
    mediaType: "video",
    auraCardId: "9",
    auraCardText: "Good energy only",
    visibility: "public",
    challengeId: "challenge-5",
    challengeTitle: "Make Their Day",
    auraCount: 89,
    commentCount: 7,
    hasGivenAura: false,
    location: "Lagos",
    createdAt: new Date(Date.now() - 1000 * 60 * 200).toISOString(),
  },
  {
    id: "moment-17",
    authorId: samira.id,
    author: samira,
    caption: "gave up my seat on a packed metro and the guy I gave it to gave me the most genuine thank you I've heard all year. small things hit different",
    mediaUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
    mediaType: "video",
    visibility: "public",
    auraCount: 256,
    commentCount: 22,
    hasGivenAura: true,
    location: "Dubai",
    createdAt: new Date(Date.now() - 1000 * 60 * 270).toISOString(),
  },
];
