import type { Notification } from "@/types";
import { MOCK_FRIENDS } from "./users";

const [riya, noah, samira, leo, hana, ishan, amara, eli, sofia, kabir] = MOCK_FRIENDS;

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: "notif-1",
    type: "aura_received",
    fromUser: riya,
    title: "Riya gave your moment Aura",
    body: '"Quiet Aura hits different."',
    relatedMomentId: "moment-5",
    isRead: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
  },
  {
    id: "notif-2",
    type: "leaderboard_moved",
    title: "You moved to #3 among friends",
    body: "+420 Aura this week. Keep it up.",
    isRead: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
  },
  {
    id: "notif-3",
    type: "streak_reminder",
    title: "Your 7-day streak is one moment away",
    body: "Do one good thing today. You're so close.",
    isRead: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
  {
    id: "notif-4",
    type: "aura_received",
    fromUser: noah,
    title: "Noah gave your moment Aura",
    body: "You inspired me to do this tomorrow.",
    relatedMomentId: "moment-5",
    isRead: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
  },
  {
    id: "notif-5",
    type: "comment_received",
    fromUser: hana,
    title: "Hana commented on your moment",
    body: "This is actually so sweet.",
    relatedMomentId: "moment-5",
    isRead: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
  },
  {
    id: "notif-6",
    type: "challenge_completed_friend",
    fromUser: amara,
    title: "Amara completed a challenge",
    body: "Amara just finished \"Make Their Day\". That's +150 Aura.",
    relatedChallengeId: "challenge-7",
    isRead: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
  },
  {
    id: "notif-7",
    type: "friend_request",
    fromUser: eli,
    title: "Eli wants to be friends",
    body: "Eli Chen sent you a friend request.",
    isRead: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 10).toISOString(),
  },
  {
    id: "notif-8",
    type: "level_reached",
    title: "You reached Level 6 — Luminous ✨",
    body: "Your Aura is becoming undeniable. Keep going.",
    isRead: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
  },
  {
    id: "notif-9",
    type: "aura_adjustment",
    title: "Aura adjustment: −15",
    body: "Reciprocal Aura pattern flagged. See Aura History for details.",
    isRead: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 200).toISOString(),
  },
  {
    id: "notif-10",
    type: "challenge_milestone",
    title: "Challenge milestone reached",
    body: 'You\'re halfway through "3-Day Aura Run". One more day.',
    relatedChallengeId: "challenge-8",
    isRead: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 120).toISOString(),
  },
  {
    id: "notif-11",
    type: "friend_accepted",
    fromUser: sofia,
    title: "Sofia accepted your friend request",
    body: "You and Sofia are now friends. Say something good.",
    isRead: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 96).toISOString(),
  },
  {
    id: "notif-12",
    type: "aura_received",
    fromUser: kabir,
    title: "Kabir gave your moment Aura",
    body: "W Aura.",
    relatedMomentId: "moment-5",
    isRead: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 168).toISOString(),
  },
];
