import type { AuraOpportunity } from "@/types";

export const MOCK_OPPORTUNITIES: AuraOpportunity[] = [
  {
    id: "opp-1",
    title: "Send a genuine thank-you",
    description: "Send a genuine thank-you message to someone who helped you recently.",
    category: "Gratitude",
    difficulty: "Easy",
    estimatedMinutes: 5,
    auraReward: 30,
    isQuietAura: true,
  },
  {
    id: "opp-2",
    title: "Include someone who seems left out",
    description: "Notice someone on the edges today and bring them in.",
    category: "Inclusion",
    difficulty: "Easy",
    estimatedMinutes: 10,
    auraReward: 40,
    isQuietAura: false,
  },
  {
    id: "opp-3",
    title: "Pick up three pieces of litter",
    description: "On your way somewhere today, pick up three pieces of litter you didn't drop.",
    category: "Environment",
    difficulty: "Easy",
    estimatedMinutes: 5,
    auraReward: 30,
    isQuietAura: false,
  },
  {
    id: "opp-4",
    title: "Check in on a friend",
    description: "Check in on a friend you haven't spoken to this week.",
    category: "Friends",
    difficulty: "Easy",
    estimatedMinutes: 5,
    auraReward: 35,
    isQuietAura: true,
  },
  {
    id: "opp-5",
    title: "Thank someone whose work goes unnoticed",
    description: "The barista, the janitor, the IT person. Tell them they're doing a great job.",
    category: "Gratitude",
    difficulty: "Easy",
    estimatedMinutes: 3,
    auraReward: 25,
    isQuietAura: false,
  },
  {
    id: "opp-6",
    title: "Listen without advice",
    description: "Let someone vent to you today. No fixing. Just listening.",
    category: "Kindness",
    difficulty: "Medium",
    estimatedMinutes: 20,
    auraReward: 50,
    isQuietAura: true,
  },
  {
    id: "opp-7",
    title: "Help a family member",
    description: "Do something helpful at home that nobody asked you to do.",
    category: "Family",
    difficulty: "Easy",
    estimatedMinutes: 15,
    auraReward: 30,
    isQuietAura: false,
  },
  {
    id: "opp-8",
    title: "Leave an encouraging comment",
    description: "Find someone's creative work online and leave a specific, genuine compliment.",
    category: "Social Aura",
    difficulty: "Easy",
    estimatedMinutes: 5,
    auraReward: 20,
    isQuietAura: false,
  },
  {
    id: "opp-9",
    title: "Hold the door open and smile",
    description: "A tiny act for a stranger. Make eye contact. Mean it.",
    category: "Community",
    difficulty: "Easy",
    estimatedMinutes: 1,
    auraReward: 15,
    isQuietAura: false,
  },
  {
    id: "opp-10",
    title: "Help someone with directions",
    description: "If you see someone looking lost, offer to help before they ask.",
    category: "Helping",
    difficulty: "Easy",
    estimatedMinutes: 5,
    auraReward: 25,
    isQuietAura: false,
  },
  {
    id: "opp-11",
    title: "Send a voice note instead of text",
    description: "Sometimes a real voice matters more than a perfectly worded message.",
    category: "Friends",
    difficulty: "Easy",
    estimatedMinutes: 5,
    auraReward: 20,
    isQuietAura: true,
  },
  {
    id: "opp-12",
    title: "Share something you learned",
    description: "Tell someone something genuinely useful or interesting you discovered this week.",
    category: "Community",
    difficulty: "Easy",
    estimatedMinutes: 10,
    auraReward: 25,
    isQuietAura: false,
  },
];
